version: '2'

volumes:
  db_data:
  nodemodules:

services:
  web:
    image: nginx:1.13
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    links:
      - app
    ports:
      - 8080:80
  
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
    links:
      - db
  
  db:
    image: mariadb:10.3
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - .:/usr/src/app
      - nodemodules:/usr/src/app/node_modules