FROM node:8.2

RUN mkdir -p /tmp
WORKDIR /tmp
COPY ./package.json /tmp/
RUN npm install


RUN mkdir -p /usr/src/app
COPY ./public /usr/src/app/public
COPY ./resources /usr/src/app/resources
RUN cp -a /tmp/node_modules /usr/src/app/ \
  && chown -R node:node /usr/src/app/

USER node
WORKDIR /usr/src/app
CMD ["npm", "start"]